# Generated by Django 3.0.6 on 2020-06-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Group'),
        ),
    ]
