# Generated by Django 3.0.6 on 2020-06-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
